# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 13:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0001_initial'),
    ]

    operations = [
        migrations.RenameField('idea', 'user', 'author'),
    ]
