# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50)),
                ('day', models.IntegerField()),
                ('fromLocation', models.CharField(default='월롱', max_length=50)),
                ('toLocation', models.CharField(default='기숙사', max_length=50)),
            ],
        ),
    ]
