# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-02 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_reserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='transport',
            field=models.IntegerField(default=0),
        ),
    ]
