# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 13:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_schedule_transport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='user',
        ),
        migrations.DeleteModel(
            name='Reserve',
        ),
        migrations.DeleteModel(
            name='Schedule',
        ),
    ]
