# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 14:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20171003_2242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='weekday',
            new_name='day',
        ),
    ]
