# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-03 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0006_auto_20171003_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
